/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dn03;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author student
 */
public class AvtomobilskoZavarovanje extends javax.swing.JFrame {

    /**
     * Creates new form AvtomobilskoZavarovanje
     */
    public AvtomobilskoZavarovanje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        Status = new javax.swing.JLabel();
        zavarovanec = new javax.swing.JPanel();
        Podatki1 = new javax.swing.JLabel();
        ime = new javax.swing.JLabel();
        ime_vnos = new javax.swing.JTextField();
        priimek = new javax.swing.JLabel();
        priimek_vnos = new javax.swing.JTextField();
        ulica = new javax.swing.JLabel();
        ulica_vnos = new javax.swing.JTextField();
        hisna_st = new javax.swing.JLabel();
        hisna_st_vnos = new javax.swing.JTextField();
        kraj = new javax.swing.JLabel();
        kraj_vnos = new javax.swing.JTextField();
        postna_st = new javax.swing.JLabel();
        postna_st_vnos = new javax.swing.JTextField();
        datum_rojstva = new javax.swing.JLabel();
        dan = new javax.swing.JComboBox();
        mesec = new javax.swing.JComboBox();
        leto = new javax.swing.JComboBox();
        izkusnje = new javax.swing.JLabel();
        mlad = new javax.swing.JRadioButton();
        izkusen = new javax.swing.JRadioButton();
        preveri_datum = new javax.swing.JButton();
        vozilo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Podatki2 = new javax.swing.JLabel();
        znamka = new javax.swing.JLabel();
        znamka_vnos = new javax.swing.JTextField();
        model = new javax.swing.JLabel();
        model_vnos = new javax.swing.JTextField();
        moc_motorja = new javax.swing.JLabel();
        prostornina_motorja = new javax.swing.JLabel();
        poraba_goriva = new javax.swing.JLabel();
        moc_motorja_vnos = new javax.swing.JTextField();
        prostornina_motorja_vnos = new javax.swing.JTextField();
        poraba_goriva_vnos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        barva = new javax.swing.JLabel();
        barva_vnos = new javax.swing.JTextField();
        stevilo_sedezev = new javax.swing.JLabel();
        stevilo_sedezev_vnos = new javax.swing.JTextField();
        vrsta_vozila = new javax.swing.JLabel();
        motor = new javax.swing.JRadioButton();
        osebni_avto = new javax.swing.JRadioButton();
        avtobus = new javax.swing.JRadioButton();
        tovornjak = new javax.swing.JRadioButton();
        traktor = new javax.swing.JRadioButton();
        registracija = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        kraj_registracije = new javax.swing.JLabel();
        kraj_registracije_vnos = new javax.swing.JTextField();
        registrska_tablica = new javax.swing.JLabel();
        registrska_tablica_vnos = new javax.swing.JTextField();
        datum_registracije = new javax.swing.JLabel();
        dan1 = new javax.swing.JComboBox();
        mesec1 = new javax.swing.JComboBox();
        leto1 = new javax.swing.JComboBox();
        preveri_datum1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        osnovno_zavarovanje = new javax.swing.JLabel();
        kasko_zavarovanje = new javax.swing.JLabel();
        dodatna_zavarovanja = new javax.swing.JLabel();
        AO = new javax.swing.JRadioButton();
        AO_plus = new javax.swing.JRadioButton();
        brez = new javax.swing.JRadioButton();
        odbitna_fransiza = new javax.swing.JRadioButton();
        polno = new javax.swing.JRadioButton();
        stekla = new javax.swing.JCheckBox();
        gume = new javax.swing.JCheckBox();
        na_parkiriscu = new javax.swing.JCheckBox();
        potniki = new javax.swing.JCheckBox();
        tretja_oseba = new javax.swing.JCheckBox();
        proti_toci = new javax.swing.JCheckBox();
        proti_kraji = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        ponastavi_vnose = new javax.swing.JButton();
        shrani_vnos = new javax.swing.JButton();
        izhod1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datoteka = new javax.swing.JMenu();
        Shrani = new javax.swing.JMenuItem();
        Izhod = new javax.swing.JMenuItem();
        Uredi = new javax.swing.JMenu();
        Ponastavi = new javax.swing.JMenuItem();
        Pomoc = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Avtomobilsko zavarovanje");

        Status.setText("Status: ");

        Podatki1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        Podatki1.setForeground(new java.awt.Color(0, 0, 204));
        Podatki1.setText("PODATKI O ZAVAROVANCU");

        ime.setText("Ime:");

        ime_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ime_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ime_vnosMouseEntered(evt);
            }
        });

        priimek.setText("Priimek:");

        priimek_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priimek_vnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                priimek_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                priimek_vnosMouseEntered(evt);
            }
        });

        ulica.setText("Ulica:");

        ulica_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ulica_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ulica_vnosMouseEntered(evt);
            }
        });

        hisna_st.setText("Hišna številka:");

        hisna_st_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hisna_st_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hisna_st_vnosMouseEntered(evt);
            }
        });

        kraj.setText("Kraj:");

        kraj_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kraj_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kraj_vnosMouseEntered(evt);
            }
        });

        postna_st.setText("Poštna številka:");

        postna_st_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                postna_st_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                postna_st_vnosMouseEntered(evt);
            }
        });
        postna_st_vnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postna_st_vnosActionPerformed(evt);
            }
        });

        datum_rojstva.setText("Datum rojstva:");

        dan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dan.setPreferredSize(new java.awt.Dimension(45, 20));

        mesec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        mesec.setPreferredSize(new java.awt.Dimension(45, 20));

        leto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        leto.setPreferredSize(new java.awt.Dimension(65, 20));

        izkusnje.setText("Izkušnje:");

        buttonGroup1.add(mlad);
        mlad.setSelected(true);
        mlad.setText("mlad voznik");

        buttonGroup1.add(izkusen);
        izkusen.setText("izkušen voznik");

        preveri_datum.setText("Preveri datum");
        preveri_datum.setPreferredSize(new java.awt.Dimension(94, 20));
        preveri_datum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preveri_datumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zavarovanecLayout = new javax.swing.GroupLayout(zavarovanec);
        zavarovanec.setLayout(zavarovanecLayout);
        zavarovanecLayout.setHorizontalGroup(
            zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zavarovanecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ulica)
                    .addComponent(Podatki1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(zavarovanecLayout.createSequentialGroup()
                        .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kraj)
                            .addComponent(ime))
                        .addGap(24, 24, 24)
                        .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(zavarovanecLayout.createSequentialGroup()
                                .addComponent(ime_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(priimek)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priimek_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(zavarovanecLayout.createSequentialGroup()
                                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ulica_vnos, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(kraj_vnos))
                                .addGap(18, 18, 18)
                                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(postna_st)
                                    .addComponent(hisna_st))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(postna_st_vnos)
                                    .addComponent(hisna_st_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(zavarovanecLayout.createSequentialGroup()
                        .addComponent(datum_rojstva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mesec, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(leto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(preveri_datum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(zavarovanecLayout.createSequentialGroup()
                        .addComponent(izkusnje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mlad)
                        .addGap(18, 18, 18)
                        .addComponent(izkusen)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        zavarovanecLayout.setVerticalGroup(
            zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zavarovanecLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Podatki1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ime)
                    .addComponent(ime_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priimek)
                    .addComponent(priimek_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kraj)
                    .addComponent(kraj_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postna_st)
                    .addComponent(postna_st_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ulica)
                    .addComponent(ulica_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hisna_st)
                    .addComponent(hisna_st_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datum_rojstva)
                    .addComponent(dan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preveri_datum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(zavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izkusnje)
                    .addComponent(mlad)
                    .addComponent(izkusen))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Podatki2.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        Podatki2.setForeground(new java.awt.Color(0, 0, 204));
        Podatki2.setText("PODATKI O VOZILU");

        znamka.setText("Znamka:");

        znamka_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                znamka_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                znamka_vnosMouseEntered(evt);
            }
        });

        model.setText("Model:");

        model_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                model_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                model_vnosMouseEntered(evt);
            }
        });

        moc_motorja.setText("Moč motorja:");

        prostornina_motorja.setText("Prostornina motorja:");

        poraba_goriva.setText("Poraba goriva:");

        moc_motorja_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moc_motorja_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moc_motorja_vnosMouseEntered(evt);
            }
        });
        moc_motorja_vnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moc_motorja_vnosActionPerformed(evt);
            }
        });

        prostornina_motorja_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prostornina_motorja_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prostornina_motorja_vnosMouseEntered(evt);
            }
        });

        poraba_goriva_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                poraba_goriva_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                poraba_goriva_vnosMouseEntered(evt);
            }
        });
        poraba_goriva_vnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poraba_goriva_vnosActionPerformed(evt);
            }
        });

        jLabel4.setText("kW");

        jLabel5.setText("cm3");

        jLabel6.setText("L/100 km");

        barva.setText("Barva:");

        barva_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barva_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barva_vnosMouseEntered(evt);
            }
        });

        stevilo_sedezev.setText("Število sedežev: ");

        stevilo_sedezev_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stevilo_sedezev_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stevilo_sedezev_vnosMouseEntered(evt);
            }
        });
        stevilo_sedezev_vnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stevilo_sedezev_vnosActionPerformed(evt);
            }
        });

        vrsta_vozila.setText("Vrsta vozila:");

        buttonGroup2.add(motor);
        motor.setText("motor");

        buttonGroup2.add(osebni_avto);
        osebni_avto.setSelected(true);
        osebni_avto.setText("osebni avto");

        buttonGroup2.add(avtobus);
        avtobus.setText("avtobus");

        buttonGroup2.add(tovornjak);
        tovornjak.setText("tovornjak");

        buttonGroup2.add(traktor);
        traktor.setText("traktor");

        javax.swing.GroupLayout voziloLayout = new javax.swing.GroupLayout(vozilo);
        vozilo.setLayout(voziloLayout);
        voziloLayout.setHorizontalGroup(
            voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(voziloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(voziloLayout.createSequentialGroup()
                        .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(voziloLayout.createSequentialGroup()
                                .addComponent(znamka)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(znamka_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(voziloLayout.createSequentialGroup()
                                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poraba_goriva)
                                    .addComponent(moc_motorja))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(voziloLayout.createSequentialGroup()
                                        .addComponent(moc_motorja_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(voziloLayout.createSequentialGroup()
                                        .addComponent(poraba_goriva_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))))
                            .addComponent(Podatki2)
                            .addGroup(voziloLayout.createSequentialGroup()
                                .addComponent(barva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(barva_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(voziloLayout.createSequentialGroup()
                                .addComponent(stevilo_sedezev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stevilo_sedezev_vnos))
                            .addGroup(voziloLayout.createSequentialGroup()
                                .addComponent(prostornina_motorja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prostornina_motorja_vnos))
                            .addGroup(voziloLayout.createSequentialGroup()
                                .addComponent(model)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(model_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(74, 74, 74))
                    .addGroup(voziloLayout.createSequentialGroup()
                        .addComponent(vrsta_vozila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(osebni_avto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(avtobus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tovornjak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(traktor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        voziloLayout.setVerticalGroup(
            voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(voziloLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Podatki2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znamka)
                    .addComponent(znamka_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model)
                    .addComponent(model_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moc_motorja)
                    .addComponent(moc_motorja_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(prostornina_motorja)
                    .addComponent(prostornina_motorja_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poraba_goriva)
                    .addComponent(poraba_goriva_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barva)
                    .addComponent(barva_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stevilo_sedezev)
                    .addComponent(stevilo_sedezev_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(voziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrsta_vozila)
                    .addComponent(osebni_avto)
                    .addComponent(avtobus)
                    .addComponent(tovornjak)
                    .addComponent(traktor)
                    .addComponent(motor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PODATKI O REGISTRACIJI");

        kraj_registracije.setText("Kraj prve registracije:");

        kraj_registracije_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kraj_registracije_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kraj_registracije_vnosMouseEntered(evt);
            }
        });

        registrska_tablica.setText("Registrska tablica:");

        registrska_tablica_vnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrska_tablica_vnosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrska_tablica_vnosMouseEntered(evt);
            }
        });
        registrska_tablica_vnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrska_tablica_vnosActionPerformed(evt);
            }
        });

        datum_registracije.setText("Datum prve registracije:");

        dan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dan1.setName(""); // NOI18N
        dan1.setPreferredSize(new java.awt.Dimension(45, 20));

        mesec1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        mesec1.setPreferredSize(new java.awt.Dimension(45, 20));

        leto1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        leto1.setPreferredSize(new java.awt.Dimension(65, 20));
        leto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leto1ActionPerformed(evt);
            }
        });

        preveri_datum1.setText("Preveri datum");
        preveri_datum1.setPreferredSize(new java.awt.Dimension(94, 20));
        preveri_datum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preveri_datum1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registracijaLayout = new javax.swing.GroupLayout(registracija);
        registracija.setLayout(registracijaLayout);
        registracijaLayout.setHorizontalGroup(
            registracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registracijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(registracijaLayout.createSequentialGroup()
                            .addComponent(registrska_tablica)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registrska_tablica_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(registracijaLayout.createSequentialGroup()
                            .addComponent(kraj_registracije)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kraj_registracije_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registracijaLayout.createSequentialGroup()
                        .addComponent(datum_registracije)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dan1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mesec1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(leto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(preveri_datum1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(registracijaLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        registracijaLayout.setVerticalGroup(
            registracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registracijaLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kraj_registracije)
                    .addComponent(kraj_registracije_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(registracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datum_registracije)
                    .addComponent(dan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preveri_datum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrska_tablica)
                    .addComponent(registrska_tablica_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("PODATKI O ZAVAROVANJU");

        osnovno_zavarovanje.setText("Osnovno zavarovanje:");

        kasko_zavarovanje.setText("Kasko zavarovanje:");

        dodatna_zavarovanja.setText("Dodatna zavarovanja:");

        buttonGroup3.add(AO);
        AO.setSelected(true);
        AO.setText("AO");

        buttonGroup3.add(AO_plus);
        AO_plus.setText("AO+");

        buttonGroup4.add(brez);
        brez.setSelected(true);
        brez.setText("brez");

        buttonGroup4.add(odbitna_fransiza);
        odbitna_fransiza.setText("odbitna franšiza");

        buttonGroup4.add(polno);
        polno.setText("polno");

        stekla.setText("stekla");

        gume.setText("gume");

        na_parkiriscu.setText("na parkirišču");

        potniki.setText("potniki");

        tretja_oseba.setText("tretja oseba");

        proti_toci.setText("proti toči");

        proti_kraji.setText("proti kraji");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(osnovno_zavarovanje)
                        .addGap(18, 18, 18)
                        .addComponent(AO)
                        .addGap(18, 18, 18)
                        .addComponent(AO_plus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kasko_zavarovanje)
                        .addGap(18, 18, 18)
                        .addComponent(brez)
                        .addGap(18, 18, 18)
                        .addComponent(odbitna_fransiza)
                        .addGap(18, 18, 18)
                        .addComponent(polno))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dodatna_zavarovanja)
                            .addComponent(proti_kraji))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stekla)
                            .addComponent(potniki))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gume)
                            .addComponent(proti_toci))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tretja_oseba)
                            .addComponent(na_parkiriscu))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(osnovno_zavarovanje)
                    .addComponent(AO)
                    .addComponent(AO_plus))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kasko_zavarovanje)
                    .addComponent(brez)
                    .addComponent(odbitna_fransiza)
                    .addComponent(polno))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodatna_zavarovanja)
                    .addComponent(stekla)
                    .addComponent(gume)
                    .addComponent(na_parkiriscu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potniki)
                    .addComponent(tretja_oseba)
                    .addComponent(proti_toci)
                    .addComponent(proti_kraji)))
        );

        ponastavi_vnose.setBackground(new java.awt.Color(255, 69, 71));
        ponastavi_vnose.setText("Ponastavi vnose");
        ponastavi_vnose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponastavi_vnoseActionPerformed(evt);
            }
        });

        shrani_vnos.setBackground(new java.awt.Color(51, 255, 51));
        shrani_vnos.setText("Shrani vnos");
        shrani_vnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shrani_vnosActionPerformed(evt);
            }
        });

        izhod1.setText("Izhod");
        izhod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzhodActionPerformed(evt);
            }
        });

        Datoteka.setMnemonic(KeyEvent.VK_D);
        Datoteka.setText("Datoteka");

        Shrani.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Shrani.setText("Shrani");
        Shrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shrani_vnosActionPerformed(evt);
            }
        });
        Datoteka.add(Shrani);

        Izhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Izhod.setText("Izhod");
        Izhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzhodActionPerformed(evt);
            }
        });
        Datoteka.add(Izhod);

        jMenuBar1.add(Datoteka);

        Uredi.setMnemonic(KeyEvent.VK_U);
        Uredi.setText("Uredi");

        Ponastavi.setText("Ponastavi vse");
        Ponastavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponastavi_vnoseActionPerformed(evt);
            }
        });
        Uredi.add(Ponastavi);

        jMenuBar1.add(Uredi);

        Pomoc.setMnemonic(KeyEvent.VK_P);
        Pomoc.setText("Pomoč");
        Pomoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PomocActionPerformed(evt);
            }
        });
        jMenuBar1.add(Pomoc);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator5)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(registracija, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
                        .addComponent(vozilo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
                        .addComponent(zavarovanec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(izhod1)
                        .addGap(18, 18, 18)
                        .addComponent(ponastavi_vnose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shrani_vnos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(zavarovanec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(izhod1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(shrani_vnos)
                        .addComponent(ponastavi_vnose)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poraba_goriva_vnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poraba_goriva_vnosActionPerformed
  
    }//GEN-LAST:event_poraba_goriva_vnosActionPerformed

    
    private void ponastavi_vnoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponastavi_vnoseActionPerformed
        // TODO add your handling code here:
        ime_vnos.setText("");
        priimek_vnos.setText("");
        ulica_vnos.setText("");
        hisna_st_vnos.setText("");
        kraj_vnos.setText("");
        postna_st_vnos.setText("");
        dan.setSelectedIndex(0);
        mesec.setSelectedIndex(0);
        leto.setSelectedIndex(0);
        mlad.setSelected(true);
        
        znamka_vnos.setText("");
        model_vnos.setText("");
        poraba_goriva_vnos.setText("");
        moc_motorja_vnos.setText("");
        prostornina_motorja_vnos.setText("");
        barva_vnos.setText("");
        stevilo_sedezev_vnos.setText("");
        osebni_avto.setSelected(true);
        
        kraj_registracije_vnos.setText("");
        registrska_tablica_vnos.setText("");
        dan1.setSelectedIndex(0);
        mesec1.setSelectedIndex(0);
        leto1.setSelectedIndex(0);
        
        AO.setSelected(true);
        brez.setSelected(true);
        stekla.setSelected(false);
        tretja_oseba.setSelected(false);
        na_parkiriscu.setSelected(false);
        proti_kraji.setSelected(false);
        proti_toci.setSelected(false);
        potniki.setSelected(false);
        gume.setSelected(false);
        
        preveri_datum.setBackground(new Color(238,238,238));
        preveri_datum1.setBackground(new Color(238,238,238));
        
        Status.setForeground(Color.black);
        Status.setText("Status: ");
    }//GEN-LAST:event_ponastavi_vnoseActionPerformed

    private void IzhodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzhodActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_IzhodActionPerformed

    private void PomocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PomocActionPerformed
        // TODO add your handling code here:
        Status.setForeground(Color.black);
        Status.setText("Status: Za pomoč se obrnite na avtorja programa.");
    }//GEN-LAST:event_PomocActionPerformed

    private void postna_st_vnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postna_st_vnosActionPerformed
        // TODO add your handling code here:
        String a = postna_st_vnos.getText();
        if (a.length() != 4) {
            Status.setForeground(Color.red);
            Status.setText("Status: Neveljavna poštna številka za Slovenijo.");
        }
        if (!a.matches("[0-9]+")) {
            Status.setForeground(Color.red);
            Status.setText("Status: Neveljavna poštna številka za Slovenijo.");
        }
    }//GEN-LAST:event_postna_st_vnosActionPerformed

    private void moc_motorja_vnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moc_motorja_vnosActionPerformed
        // TODO add your handling code here:
        String a = moc_motorja_vnos.getText();
        if (a.length() > 3) {
            Status.setForeground(Color.red);
            Status.setText("Status: Nepravilen vnos za moč motorja.");
        }
    }//GEN-LAST:event_moc_motorja_vnosActionPerformed

    private void stevilo_sedezev_vnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stevilo_sedezev_vnosActionPerformed
        // TODO add your handling code here:
        String a = stevilo_sedezev_vnos.getText();
        int b = Integer.parseInt(a);
        if (b > 100 || b < 0) {
            Status.setForeground(Color.red);
            Status.setText("Status: Nepravilen vnos za število sedežev.");
        }
    }//GEN-LAST:event_stevilo_sedezev_vnosActionPerformed

    private void registrska_tablica_vnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrska_tablica_vnosActionPerformed
        // TODO add your handling code here:
        String a = registrska_tablica_vnos.getText();
        if (a.length() > 9) {
            Status.setForeground(Color.red);
            Status.setText("Status: Nepravilen vnos registrske tablice.");
        }
    }//GEN-LAST:event_registrska_tablica_vnosActionPerformed

    private void preveri_datumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preveri_datumActionPerformed
        // TODO add your handling code here:
        int d_index = dan.getSelectedIndex();
        int d = d_index+1;
        int m_index = mesec.getSelectedIndex();
        int m = m_index+1;
        int l_index = leto.getSelectedIndex();
        int l = l_index+1930;
        
        boolean pravilno = true;
        boolean prestopno = false;
        
        if ((l%4 == 0 && l%100 != 0) || (l%4 == 0 && l%100 != 0 && l%400 == 0)) {
            prestopno = true;
        }
        
        if (d == 31 && (m == 4 || m == 6 || m == 9 || m == 11)) {            
            pravilno = false;
        }
        
        if (m == 2 && d > 29) {
            pravilno = false;
        }
        
        if (m == 2 && d == 29 && !prestopno) {
            pravilno = false;
        }
        
        if (!pravilno) {
            Status.setForeground(Color.red);
            Status.setText("Status: Izbran datum ni veljaven.");
            preveri_datum.setBackground(new Color(255,69,7));
        }
        else {
            Status.setForeground(Color.black);
            Status.setText("Status: Izbran datum je veljaven.");
            preveri_datum.setBackground(Color.green);
        }
    }//GEN-LAST:event_preveri_datumActionPerformed

    private void leto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leto1ActionPerformed

    private void preveri_datum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preveri_datum1ActionPerformed
        // TODO add your handling code here:
        int d_index = dan1.getSelectedIndex();
        int d = d_index+1;
        int m_index = mesec1.getSelectedIndex();
        int m = m_index+1;
        int l_index = leto1.getSelectedIndex();
        int l = l_index+1980;
        
        boolean pravilno = true;
        boolean prestopno = false;
        
        if ((l%4 == 0 && l%100 != 0) || (l%4 == 0 && l%100 == 0 && l%400 == 0)) {
            prestopno = true;
        }
        
        if (d == 31 && (m == 4 || m == 6 || m == 9 || m == 11)) {            
            pravilno = false;
        }
        
        if (m == 2 && d > 29) {
            pravilno = false;
        }
        
        if (m == 2 && d == 29 && !prestopno) {
            pravilno = false;
        }
        
        if (!pravilno) {
            Status.setForeground(Color.red);
            Status.setText("Status: Izbran datum ni veljaven.");
            preveri_datum1.setBackground(new Color(255,69,7));
        }
        else {
            Status.setForeground(Color.black);
            Status.setText("Status: Izbran datum je veljaven.");
            preveri_datum1.setBackground(Color.green);
        }
    }//GEN-LAST:event_preveri_datum1ActionPerformed

    private void shrani_vnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shrani_vnosActionPerformed
        // TODO add your handling code here:
        boolean prazno = false;
        
        if (ime_vnos.getText().equals("") || priimek_vnos.getText().equals("") || ulica_vnos.getText().equals("") || hisna_st_vnos.getText().equals("") ||
                kraj_vnos.getText().equals("") || postna_st_vnos.getText().equals("") || znamka_vnos.getText().equals("") ||
                model_vnos.getText().equals("") || poraba_goriva_vnos.getText().equals("") || moc_motorja_vnos.getText().equals("") ||
                prostornina_motorja_vnos.getText().equals("") || barva_vnos.getText().equals("") || stevilo_sedezev_vnos.getText().equals("") ||
                kraj_registracije_vnos.getText().equals("") || registrska_tablica_vnos.getText().equals("")) 
        {
            Status.setForeground(Color.red);
            Status.setText("Status: Izpolnite vsa polja!");
            prazno = true;
        }
        
        if(!prazno) {
            
            try {
                
                File f = new File ("/home/student/FRI/KČR/DN03/Izpolnjen_obrazec.txt");
                if (!f.exists()) {
                    f.createNewFile();
                }    
                
                FileWriter fw = new FileWriter(f.getAbsoluteFile());
                BufferedWriter bw = new BufferedWriter(fw);
                
                bw.write("PODATKI O ZAVAROVANCU \n");
                bw.write("Ime: " + ime_vnos.getText() + "\n");
                bw.write("Priimek: " + priimek_vnos.getText() +"\n");
                bw.write("Kraj: " + kraj_vnos.getText() +"\n");
                bw.write("Poštna številka: " + postna_st_vnos.getText() +"\n");
                bw.write("Ulica: " + ulica_vnos.getText() +"\n");
                bw.write("Hišna številka: " + hisna_st_vnos.getText() +"\n");
                int d = dan.getSelectedIndex() + 1;
                int m = mesec.getSelectedIndex() + 1;
                int l = leto.getSelectedIndex() + 1930;
                bw.write("Datum rojstva: " + d + ". " + m + ". " + l + "\n");
                if (mlad.isSelected())  bw.write("Izkušnje: " + "mlad voznik" + "\n\n");
                else  bw.write("Izkušnje: " + "izkušen voznik" + "\n\n");
                
                bw.write("PODATKI O VOZILU\n");
                bw.write("Znamka: " + znamka_vnos.getText() + "\n");
                bw.write("Model: " + model_vnos.getText() + "\n");
                bw.write("Moč motorja: " + moc_motorja_vnos.getText() + " kW\n");
                bw.write("Prostornina motorja: " + prostornina_motorja_vnos.getText() + "cm3\n");
                bw.write("Poraba goriva: " + poraba_goriva_vnos.getText() + "L/100km\n");
                bw.write("Barva: " + barva_vnos.getText() + "\n");
                bw.write("Število sedežev: " + stevilo_sedezev_vnos.getText() + "\n");
                if (osebni_avto.isSelected())  bw.write("Vrsta vozila: osebni avto\n\n");
                else if (motor.isSelected())  bw.write("Vrsta vozila: motor\n\n");
                else if (tovornjak.isSelected())  bw.write("Vrsta vozila: tovornjak\n\n");
                else if (traktor.isSelected())  bw.write("Vrsta vozila: traktor\n\n");
                else if (avtobus.isSelected())  bw.write("Vrsta vozila: avtobus\n\n");
                
                bw.write("PODATKI O REGISTRACIJI\n");
                bw.write("Kraj prve registracije: " + kraj_registracije_vnos.getText() + "\n");
                int d1 = dan1.getSelectedIndex() + 1;
                int m1 = mesec1.getSelectedIndex() + 1;
                int l1 = leto1.getSelectedIndex() + 1980;
                bw.write("Datum prva registracije: " + d1 + ". " + m1 + ". " + l1 + "\n");
                bw.write("Registrska tablica: " + registrska_tablica_vnos.getText() +"\n\n");
                
                bw.write("PODATKI O ZAVAROVANJU\n");
                if (AO.isSelected())  bw.write("Osnovno zavarovanje: AO\n");
                else if (AO_plus.isSelected())  bw.write("Osnovno zavarovanje: AO+\n");
                if (brez.isSelected())  bw.write("Kasko zavarovanje: brez\n");
                else if (odbitna_fransiza.isSelected())  bw.write("Kasko zavarovanje: odbitna franšiza\n");
                else if (polno.isSelected())  bw.write("Kasko zavarovanje: polno\n");
                bw.write("Dodatna zavarovanja: ");
                if (stekla.isSelected())  bw.write("stekla, ");
                if (gume.isSelected())  bw.write("gume, ");
                if (na_parkiriscu.isSelected())  bw.write("na parkirišču, ");
                if (proti_kraji.isSelected())  bw.write("proti kraji, ");
                if (proti_toci.isSelected())  bw.write("proti toči, ");
                if (tretja_oseba.isSelected())  bw.write("potniki, ");
                if (potniki.isSelected())  bw.write("potniki");
                
                
                bw.close();
                
                Status.setForeground(new Color (0,200,0));
                Status.setText("Status: Podatki uspešno shranjeni.");
                
            }
            catch (IOException e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_shrani_vnosActionPerformed

    private void ime_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ime_vnosMouseEntered
        // TODO add your handling code here:
        ime_vnos.setBackground(new Color (200, 255, 255));
    }//GEN-LAST:event_ime_vnosMouseEntered

    private void ime_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ime_vnosMouseExited
        // TODO add your handling code here:
        ime_vnos.setBackground(Color.white);
    }//GEN-LAST:event_ime_vnosMouseExited

    private void priimek_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priimek_vnosMouseEntered
        // TODO add your handling code here:
        priimek_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_priimek_vnosMouseEntered

    private void priimek_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priimek_vnosMouseExited
        // TODO add your handling code here:
        priimek_vnos.setBackground(Color.white);
    }//GEN-LAST:event_priimek_vnosMouseExited

    private void kraj_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kraj_vnosMouseEntered
        // TODO add your handling code here:
        kraj_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_kraj_vnosMouseEntered

    private void postna_st_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postna_st_vnosMouseEntered
        // TODO add your handling code here:
        postna_st_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_postna_st_vnosMouseEntered

    private void postna_st_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postna_st_vnosMouseExited
        // TODO add your handling code here:
        postna_st_vnos.setBackground(Color.white);
    }//GEN-LAST:event_postna_st_vnosMouseExited

    private void kraj_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kraj_vnosMouseExited
        // TODO add your handling code here:
        kraj_vnos.setBackground(Color.white);
    }//GEN-LAST:event_kraj_vnosMouseExited

    private void ulica_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ulica_vnosMouseEntered
        // TODO add your handling code here:
        ulica_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_ulica_vnosMouseEntered

    private void ulica_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ulica_vnosMouseExited
        // TODO add your handling code here:
        ulica_vnos.setBackground(Color.white);
    }//GEN-LAST:event_ulica_vnosMouseExited

    private void hisna_st_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hisna_st_vnosMouseEntered
        // TODO add your handling code here:
        hisna_st_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_hisna_st_vnosMouseEntered

    private void hisna_st_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hisna_st_vnosMouseExited
        // TODO add your handling code here:
        hisna_st_vnos.setBackground(Color.white);
    }//GEN-LAST:event_hisna_st_vnosMouseExited

    private void znamka_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_znamka_vnosMouseEntered
        // TODO add your handling code here:
        znamka_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_znamka_vnosMouseEntered

    private void znamka_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_znamka_vnosMouseExited
        // TODO add your handling code here:
        znamka_vnos.setBackground(Color.white);
    }//GEN-LAST:event_znamka_vnosMouseExited

    private void model_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_model_vnosMouseEntered
        // TODO add your handling code here:
        model_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_model_vnosMouseEntered

    private void model_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_model_vnosMouseExited
        // TODO add your handling code here:
        model_vnos.setBackground(Color.white);
    }//GEN-LAST:event_model_vnosMouseExited

    private void moc_motorja_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moc_motorja_vnosMouseEntered
        // TODO add your handling code here:
        moc_motorja_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_moc_motorja_vnosMouseEntered

    private void moc_motorja_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moc_motorja_vnosMouseExited
        // TODO add your handling code here:
        moc_motorja_vnos.setBackground(Color.white);
    }//GEN-LAST:event_moc_motorja_vnosMouseExited

    private void prostornina_motorja_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prostornina_motorja_vnosMouseEntered
        // TODO add your handling code here:
        prostornina_motorja_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_prostornina_motorja_vnosMouseEntered

    private void prostornina_motorja_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prostornina_motorja_vnosMouseExited
        // TODO add your handling code here:
        prostornina_motorja_vnos.setBackground(Color.white);
    }//GEN-LAST:event_prostornina_motorja_vnosMouseExited

    private void poraba_goriva_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poraba_goriva_vnosMouseEntered
        // TODO add your handling code here:
        poraba_goriva_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_poraba_goriva_vnosMouseEntered

    private void poraba_goriva_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poraba_goriva_vnosMouseExited
        // TODO add your handling code here:
        poraba_goriva_vnos.setBackground(Color.white);
    }//GEN-LAST:event_poraba_goriva_vnosMouseExited

    private void barva_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barva_vnosMouseEntered
        // TODO add your handling code here:
        barva_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_barva_vnosMouseEntered

    private void barva_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barva_vnosMouseExited
        // TODO add your handling code here:
        barva_vnos.setBackground(Color.white);
    }//GEN-LAST:event_barva_vnosMouseExited

    private void stevilo_sedezev_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stevilo_sedezev_vnosMouseEntered
        // TODO add your handling code here:
        stevilo_sedezev_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_stevilo_sedezev_vnosMouseEntered

    private void stevilo_sedezev_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stevilo_sedezev_vnosMouseExited
        // TODO add your handling code here:
        stevilo_sedezev_vnos.setBackground(Color.white);
    }//GEN-LAST:event_stevilo_sedezev_vnosMouseExited

    private void kraj_registracije_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kraj_registracije_vnosMouseEntered
        // TODO add your handling code here:
        kraj_registracije_vnos.setBackground(new Color(200,255,255));
    }//GEN-LAST:event_kraj_registracije_vnosMouseEntered

    private void kraj_registracije_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kraj_registracije_vnosMouseExited
        // TODO add your handling code here:
        kraj_registracije_vnos.setBackground(Color.white);
    }//GEN-LAST:event_kraj_registracije_vnosMouseExited

    private void registrska_tablica_vnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrska_tablica_vnosMouseEntered
        // TODO add your handling code here:
        registrska_tablica_vnos.setBackground(new Color (200,255,255));
    }//GEN-LAST:event_registrska_tablica_vnosMouseEntered

    private void registrska_tablica_vnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrska_tablica_vnosMouseExited
        // TODO add your handling code here:
        registrska_tablica_vnos.setBackground(Color.white);
    }//GEN-LAST:event_registrska_tablica_vnosMouseExited
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvtomobilskoZavarovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvtomobilskoZavarovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvtomobilskoZavarovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvtomobilskoZavarovanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvtomobilskoZavarovanje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AO;
    private javax.swing.JRadioButton AO_plus;
    private javax.swing.JMenu Datoteka;
    private javax.swing.JMenuItem Izhod;
    private javax.swing.JLabel Podatki1;
    private javax.swing.JLabel Podatki2;
    private javax.swing.JMenu Pomoc;
    private javax.swing.JMenuItem Ponastavi;
    private javax.swing.JMenuItem Shrani;
    private javax.swing.JLabel Status;
    private javax.swing.JMenu Uredi;
    private javax.swing.JRadioButton avtobus;
    private javax.swing.JLabel barva;
    private javax.swing.JTextField barva_vnos;
    private javax.swing.JRadioButton brez;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox dan;
    private javax.swing.JComboBox dan1;
    private javax.swing.JLabel datum_registracije;
    private javax.swing.JLabel datum_rojstva;
    private javax.swing.JLabel dodatna_zavarovanja;
    private javax.swing.JCheckBox gume;
    private javax.swing.JLabel hisna_st;
    private javax.swing.JTextField hisna_st_vnos;
    private javax.swing.JLabel ime;
    private javax.swing.JTextField ime_vnos;
    private javax.swing.JButton izhod1;
    private javax.swing.JRadioButton izkusen;
    private javax.swing.JLabel izkusnje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel kasko_zavarovanje;
    private javax.swing.JLabel kraj;
    private javax.swing.JLabel kraj_registracije;
    private javax.swing.JTextField kraj_registracije_vnos;
    private javax.swing.JTextField kraj_vnos;
    private javax.swing.JComboBox leto;
    private javax.swing.JComboBox leto1;
    private javax.swing.JComboBox mesec;
    private javax.swing.JComboBox mesec1;
    private javax.swing.JRadioButton mlad;
    private javax.swing.JLabel moc_motorja;
    private javax.swing.JTextField moc_motorja_vnos;
    private javax.swing.JLabel model;
    private javax.swing.JTextField model_vnos;
    private javax.swing.JRadioButton motor;
    private javax.swing.JCheckBox na_parkiriscu;
    private javax.swing.JRadioButton odbitna_fransiza;
    private javax.swing.JRadioButton osebni_avto;
    private javax.swing.JLabel osnovno_zavarovanje;
    private javax.swing.JRadioButton polno;
    private javax.swing.JButton ponastavi_vnose;
    private javax.swing.JLabel poraba_goriva;
    private javax.swing.JTextField poraba_goriva_vnos;
    private javax.swing.JLabel postna_st;
    private javax.swing.JTextField postna_st_vnos;
    private javax.swing.JCheckBox potniki;
    private javax.swing.JButton preveri_datum;
    private javax.swing.JButton preveri_datum1;
    private javax.swing.JLabel priimek;
    private javax.swing.JTextField priimek_vnos;
    private javax.swing.JLabel prostornina_motorja;
    private javax.swing.JTextField prostornina_motorja_vnos;
    private javax.swing.JCheckBox proti_kraji;
    private javax.swing.JCheckBox proti_toci;
    private javax.swing.JPanel registracija;
    private javax.swing.JLabel registrska_tablica;
    private javax.swing.JTextField registrska_tablica_vnos;
    private javax.swing.JButton shrani_vnos;
    private javax.swing.JCheckBox stekla;
    private javax.swing.JLabel stevilo_sedezev;
    private javax.swing.JTextField stevilo_sedezev_vnos;
    private javax.swing.JRadioButton tovornjak;
    private javax.swing.JRadioButton traktor;
    private javax.swing.JCheckBox tretja_oseba;
    private javax.swing.JLabel ulica;
    private javax.swing.JTextField ulica_vnos;
    private javax.swing.JPanel vozilo;
    private javax.swing.JLabel vrsta_vozila;
    private javax.swing.JPanel zavarovanec;
    private javax.swing.JLabel znamka;
    private javax.swing.JTextField znamka_vnos;
    // End of variables declaration//GEN-END:variables
}
