

package DN01;

import java.awt.Container;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.plaf.FileChooserUI;
/**
 *
 * @author student
 */
public class DN01 extends javax.swing.JFrame {

    /**
     * Creates new form DN01
     */
    public DN01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFC1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        m1 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        r1 = new javax.swing.JButton();
        k1 = new javax.swing.JButton();
        o1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        z2 = new javax.swing.JButton();
        e2 = new javax.swing.JButton();
        m2 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PoljeZaVnos = new javax.swing.JTextField();
        Izvedi = new javax.swing.JButton();
        Dodaj = new javax.swing.JRadioButton();
        OdstraniPrvega = new javax.swing.JRadioButton();
        OdstraniIzbranega = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        PrepovejDvojnike = new javax.swing.JCheckBox();
        VrsticaZaSporocila = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        StatusnaVrstica = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datoteka = new javax.swing.JMenu();
        Odpri = new javax.swing.JMenuItem();
        Pobriši = new javax.swing.JMenuItem();
        Izhod = new javax.swing.JMenuItem();
        Izbire1 = new javax.swing.JMenu();
        M1 = new javax.swing.JMenuItem();
        A1 = new javax.swing.JMenuItem();
        R1 = new javax.swing.JMenuItem();
        K1 = new javax.swing.JMenuItem();
        O1 = new javax.swing.JMenuItem();
        Izbire2 = new javax.swing.JMenu();
        Z2 = new javax.swing.JMenuItem();
        E2 = new javax.swing.JMenuItem();
        M2 = new javax.swing.JMenuItem();
        A2 = new javax.swing.JMenuItem();
        N2 = new javax.swing.JMenuItem();
        Pomoč = new javax.swing.JMenu();
        Navodila = new javax.swing.JMenuItem();

        jFC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFC1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DN01");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jToolBar1.setRollover(true);

        m1.setText("Izbire1 M");
        m1.setFocusable(false);
        m1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        jToolBar1.add(m1);

        a1.setText("Izbire1 A");
        a1.setFocusable(false);
        a1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jToolBar1.add(a1);

        r1.setText("Izbire1 R");
        r1.setFocusable(false);
        r1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        r1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jToolBar1.add(r1);

        k1.setText("Izbire1 K");
        k1.setFocusable(false);
        k1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        k1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        k1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k1ActionPerformed(evt);
            }
        });
        jToolBar1.add(k1);

        o1.setText("Izbire1 O");
        o1.setFocusable(false);
        o1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        o1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        o1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o1ActionPerformed(evt);
            }
        });
        jToolBar1.add(o1);
        jToolBar1.add(jSeparator1);

        z2.setText("Izbire2 Z");
        z2.setFocusable(false);
        z2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        z2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        z2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2ActionPerformed(evt);
            }
        });
        jToolBar1.add(z2);

        e2.setText("Izbire2 E");
        e2.setFocusable(false);
        e2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        e2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        jToolBar1.add(e2);

        m2.setText("Izbire2 M");
        m2.setFocusable(false);
        m2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        m2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m2ActionPerformed(evt);
            }
        });
        jToolBar1.add(m2);

        a2.setText("Izbire2 A");
        a2.setFocusable(false);
        a2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        a2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jToolBar1.add(a2);

        n2.setText("Izbire2 N");
        n2.setFocusable(false);
        n2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        n2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        jToolBar1.add(n2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        PoljeZaVnos.setBackground(new java.awt.Color(153, 255, 153));

        Izvedi.setText("Izvedi izbrano akcijo");
        Izvedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzvediActionPerformed(evt);
            }
        });

        Dodaj.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(Dodaj);
        Dodaj.setText("Dodaj");

        OdstraniPrvega.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(OdstraniPrvega);
        OdstraniPrvega.setText("Odstrani prvega");

        OdstraniIzbranega.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(OdstraniIzbranega);
        OdstraniIzbranega.setText("Odstrani izbranega");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ljubljana", "Kranj", "Celje", "Maribor", "Koper" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        PrepovejDvojnike.setBackground(new java.awt.Color(204, 255, 204));
        PrepovejDvojnike.setText("Prepovej dvojnike");

        VrsticaZaSporocila.setText("Vrstica za sporočila: ");

        jLabel1.setText("Polje za vnos teksta:");

        StatusnaVrstica.setText("  Statusna vrstica: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VrsticaZaSporocila, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PoljeZaVnos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44)
                                .addComponent(OdstraniPrvega)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PrepovejDvojnike)
                                    .addComponent(OdstraniIzbranega))))
                        .addGap(299, 299, 299))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Izvedi))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(StatusnaVrstica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PoljeZaVnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dodaj)
                    .addComponent(OdstraniPrvega)
                    .addComponent(OdstraniIzbranega))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Izvedi)
                    .addComponent(PrepovejDvojnike))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(VrsticaZaSporocila, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(StatusnaVrstica, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setForeground(new java.awt.Color(50, 50, 50));

        Datoteka.setMnemonic(KeyEvent.VK_D);
        Datoteka.setText("Datoteka");

        Odpri.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Odpri.setMnemonic(KeyEvent.VK_O);
        Odpri.setText("Odpri");
        Odpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdpriActionPerformed(evt);
            }
        });
        Datoteka.add(Odpri);

        Pobriši.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Pobriši.setMnemonic(KeyEvent.VK_P);
        Pobriši.setText("Pobriši");
        Pobriši.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PobrišiActionPerformed(evt);
            }
        });
        Datoteka.add(Pobriši);

        Izhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Izhod.setMnemonic(KeyEvent.VK_I);
        Izhod.setText("Izhod");
        Izhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzhodActionPerformed(evt);
            }
        });
        Datoteka.add(Izhod);

        jMenuBar1.add(Datoteka);

        Izbire1.setMnemonic(KeyEvent.VK_1);
        Izbire1.setText("Izbire1");

        M1.setMnemonic(KeyEvent.VK_M);
        M1.setText("Izbire1 M ");
        M1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M1ActionPerformed(evt);
            }
        });
        Izbire1.add(M1);

        A1.setMnemonic(KeyEvent.VK_A);
        A1.setText("Izbire1 A");
        A1.setActionCommand("jMenuItem5");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        Izbire1.add(A1);

        R1.setMnemonic(KeyEvent.VK_R);
        R1.setText("Izbire1 R");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        Izbire1.add(R1);

        K1.setMnemonic(KeyEvent.VK_K
        );
        K1.setText("Izbire1 K");
        K1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K1ActionPerformed(evt);
            }
        });
        Izbire1.add(K1);

        O1.setMnemonic(KeyEvent.VK_O);
        O1.setText("Izbire1 O");
        O1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                O1ActionPerformed(evt);
            }
        });
        Izbire1.add(O1);

        jMenuBar1.add(Izbire1);

        Izbire2.setMnemonic(KeyEvent.VK_2);
        Izbire2.setText("Izbire2");

        Z2.setMnemonic(KeyEvent.VK_Z);
        Z2.setText("Izbire2 Z");
        Z2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Z2ActionPerformed(evt);
            }
        });
        Izbire2.add(Z2);

        E2.setMnemonic(KeyEvent.VK_E);
        E2.setText("Izbire2 E");
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        Izbire2.add(E2);

        M2.setMnemonic(KeyEvent.VK_M);
        M2.setText("Izbire2 M");
        M2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M2ActionPerformed(evt);
            }
        });
        Izbire2.add(M2);

        A2.setMnemonic(KeyEvent.VK_A);
        A2.setText("Izbire2 A");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        Izbire2.add(A2);

        N2.setMnemonic(KeyEvent.VK_N);
        N2.setText("Izbire2 N");
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        Izbire2.add(N2);

        jMenuBar1.add(Izbire2);

        Pomoč.setMnemonic(KeyEvent.VK_P);
        Pomoč.setText("Pomoč");

        Navodila.setMnemonic(KeyEvent.VK_N);
        Navodila.setText("Navodila");
        Navodila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavodilaActionPerformed(evt);
            }
        });
        Pomoč.add(Navodila);

        jMenuBar1.add(Pomoč);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                           
    
    private void IzhodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzhodActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_IzhodActionPerformed

    private void PobrišiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PobrišiActionPerformed
        // TODO add your handling code here:
        VrsticaZaSporocila.setText("Vrstica za sporočila: ");
        StatusnaVrstica.setText("  Statusna vrstica ");
    }//GEN-LAST:event_PobrišiActionPerformed

    private void k1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"K";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_k1ActionPerformed

    private void OdpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdpriActionPerformed
        // TODO add your handling code here:
        jFC1.showOpenDialog(Odpri);
    }//GEN-LAST:event_OdpriActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formKeyPressed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"M";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_m1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"A";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_a1ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"R";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_r1ActionPerformed

    private void o1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"O";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_o1ActionPerformed

    private void z2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"Z";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_z2ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"E";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_e2ActionPerformed

    private void m2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"M";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_m2ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"A";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_a2ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"N";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_n2ActionPerformed

    private void M1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"M";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_M1ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"A";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_A1ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"R";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_R1ActionPerformed

    private void K1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"K";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_K1ActionPerformed

    private void O1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_O1ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"O";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_O1ActionPerformed

    private void Z2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Z2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"Z";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_Z2ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"E";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_E2ActionPerformed

    private void M2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"M";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_M2ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"A";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_A2ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        // TODO add your handling code here:
        String s = StatusnaVrstica.getText();
        String izpis = s+"N";
        StatusnaVrstica.setText(izpis);
    }//GEN-LAST:event_N2ActionPerformed

    private void jFC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFC1ActionPerformed

    private void NavodilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavodilaActionPerformed
        // TODO add your handling code here:
        VrsticaZaSporocila.setText("Vrstica za sporočila: Navodila so navedena na spletni strani učilnice FRI pri predmetu KČR (1. naloga).");
    }//GEN-LAST:event_NavodilaActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int a = (int) jSpinner1.getValue();
        int count = jComboBox1.getItemCount();
        if (a>=count) {
            VrsticaZaSporocila.setText("Vrstica za sporočila: Ni elementa");
        }
        else {
            String s = jComboBox1.getItemAt(a).toString();
            VrsticaZaSporocila.setText("Vrstica za sporočila: "+s);
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void IzvediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzvediActionPerformed
        // TODO add your handling code here:
        String vnos = PoljeZaVnos.getText();

        if (Dodaj.isSelected()) {
            boolean jeNotri = false;
            int a = jComboBox1.getItemCount();
            String[] s = new String [a];
            for (int i=0; i<a; i++) {
                s[i] = jComboBox1.getItemAt(i).toString();
                if (s[i].equals(vnos)) {
                    jeNotri = true;
                }
            }
            if ((!vnos.isEmpty() && !jeNotri) || (!vnos.isEmpty() && jeNotri && !PrepovejDvojnike.isSelected())) {
                jComboBox1.addItem(vnos);
            }
            VrsticaZaSporocila.setText("Vrstica za sporočila: Dodajam");
        }
        else if (OdstraniPrvega.isSelected()) {
            if (jComboBox1.getItemCount() != 0) {
                jComboBox1.removeItemAt(0);
            }
            VrsticaZaSporocila.setText("Vrstica za sporočila: Odstranjujem prvega");
        }
        else if (OdstraniIzbranega.isSelected()) {
            if (jComboBox1.getItemCount() != 0) {
                int i = jComboBox1.getSelectedIndex();
                jComboBox1.removeItemAt(i);
            }
            VrsticaZaSporocila.setText("Vrstica za sporočila: Odstranjujem izbranega");
        }

    }//GEN-LAST:event_IzvediActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DN01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DN01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DN01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DN01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DN01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem A1;
    private javax.swing.JMenuItem A2;
    private javax.swing.JMenu Datoteka;
    private javax.swing.JRadioButton Dodaj;
    private javax.swing.JMenuItem E2;
    private javax.swing.JMenu Izbire1;
    private javax.swing.JMenu Izbire2;
    private javax.swing.JMenuItem Izhod;
    private javax.swing.JButton Izvedi;
    private javax.swing.JMenuItem K1;
    private javax.swing.JMenuItem M1;
    private javax.swing.JMenuItem M2;
    private javax.swing.JMenuItem N2;
    private javax.swing.JMenuItem Navodila;
    private javax.swing.JMenuItem O1;
    private javax.swing.JMenuItem Odpri;
    private javax.swing.JRadioButton OdstraniIzbranega;
    private javax.swing.JRadioButton OdstraniPrvega;
    private javax.swing.JMenuItem Pobriši;
    private javax.swing.JTextField PoljeZaVnos;
    private javax.swing.JMenu Pomoč;
    private javax.swing.JCheckBox PrepovejDvojnike;
    private javax.swing.JMenuItem R1;
    private javax.swing.JLabel StatusnaVrstica;
    private javax.swing.JLabel VrsticaZaSporocila;
    private javax.swing.JMenuItem Z2;
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton e2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFileChooser jFC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton k1;
    private javax.swing.JButton m1;
    private javax.swing.JButton m2;
    private javax.swing.JButton n2;
    private javax.swing.JButton o1;
    private javax.swing.JButton r1;
    private javax.swing.JButton z2;
    // End of variables declaration//GEN-END:variables
}
