/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dn04;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author student
 */
public class IzposojevalnicaAvtomobilov extends javax.swing.JFrame {

    /**
     * Creates new form IzposojevalnicaAvtomobilov
     */
    public IzposojevalnicaAvtomobilov() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                buttonGroup1 = new javax.swing.ButtonGroup();
                jSeparator2 = new javax.swing.JSeparator();
                buttonGroup2 = new javax.swing.ButtonGroup();
                buttonGroup3 = new javax.swing.ButtonGroup();
                buttonGroup4 = new javax.swing.ButtonGroup();
                status = new javax.swing.JLabel();
                najem = new javax.swing.JPanel();
                o_najemu = new javax.swing.JLabel();
                datum_prevzema = new javax.swing.JLabel();
                datum_vrnitve = new javax.swing.JLabel();
                dan_prevzema = new javax.swing.JComboBox();
                mesec_prevzema = new javax.swing.JComboBox();
                leto_prevzema = new javax.swing.JComboBox();
                dan_vrnitve = new javax.swing.JComboBox();
                mesec_vrnitve = new javax.swing.JComboBox();
                leto_vrnitve = new javax.swing.JComboBox();
                ura_prevzema = new javax.swing.JLabel();
                ura_vrnitve = new javax.swing.JLabel();
                ura_prevzema_vnos = new javax.swing.JSpinner();
                ura_vrnitve_vnos = new javax.swing.JSpinner();
                mesto_prevzema = new javax.swing.JLabel();
                mesto_prevzema_vnos = new javax.swing.JComboBox();
                mesto_vrnitve = new javax.swing.JLabel();
                mesto_prevzema_vnos1 = new javax.swing.JComboBox();
                jSeparator1 = new javax.swing.JSeparator();
                avtomobil = new javax.swing.JPanel();
                o_avtomobilu = new javax.swing.JLabel();
                velikost_avtomobila = new javax.swing.JLabel();
                tip_avtomobila = new javax.swing.JLabel();
                majhen = new javax.swing.JRadioButton();
                srednji = new javax.swing.JRadioButton();
                velik = new javax.swing.JRadioButton();
                tip_majhen = new javax.swing.JComboBox();
                tip_srednji = new javax.swing.JComboBox();
                tip_velik = new javax.swing.JComboBox();
                menjalnik = new javax.swing.JLabel();
                rocni = new javax.swing.JRadioButton();
                avtomatski = new javax.swing.JRadioButton();
                motor = new javax.swing.JLabel();
                bencinski = new javax.swing.JRadioButton();
                dizelski = new javax.swing.JRadioButton();
                jSeparator3 = new javax.swing.JSeparator();
                cena_za_dan = new javax.swing.JLabel();
                cena_na_dan_izpis = new javax.swing.JTextField();
                skupna_cena = new javax.swing.JLabel();
                skupna_cena_izpis = new javax.swing.JTextField();
                jSeparator4 = new javax.swing.JSeparator();
                podatki = new javax.swing.JPanel();
                osebni_podatki = new javax.swing.JLabel();
                ime = new javax.swing.JLabel();
                ime_vnos = new javax.swing.JTextField();
                priimek = new javax.swing.JLabel();
                priimek_vnos = new javax.swing.JTextField();
                starost = new javax.swing.JLabel();
                starost_vnos = new javax.swing.JSpinner();
                naslov = new javax.swing.JLabel();
                naslov_vnos = new javax.swing.JTextField();
                kraj = new javax.swing.JLabel();
                kraj_vnos = new javax.swing.JTextField();
                postna_st = new javax.swing.JLabel();
                postna_st_vnos = new javax.swing.JTextField();
                mail = new javax.swing.JLabel();
                mail_vnos = new javax.swing.JTextField();
                telefon = new javax.swing.JLabel();
                telefon_vnos = new javax.swing.JTextField();
                cas_izpita = new javax.swing.JLabel();
                cas_izpita_vnos = new javax.swing.JSpinner();
                dodatno_zavarovanje = new javax.swing.JLabel();
                dod_zavarovanje = new javax.swing.JCheckBox();
                jSeparator5 = new javax.swing.JSeparator();
                placilo = new javax.swing.JPanel();
                nacin_placila = new javax.swing.JLabel();
                gotovina = new javax.swing.JRadioButton();
                kartica = new javax.swing.JRadioButton();
                st_kreditne_kartice = new javax.swing.JLabel();
                skrita_st_kreditne_kartice = new javax.swing.JPasswordField();
                vidna_st_kreditne_kartice = new javax.swing.JTextField();
                ccv = new javax.swing.JLabel();
                ccv_vnos = new javax.swing.JPasswordField();
                placaj = new javax.swing.JButton();
                potrdi = new javax.swing.JButton();
                jSeparator6 = new javax.swing.JSeparator();
                jMenuBar1 = new javax.swing.JMenuBar();
                Datoteka = new javax.swing.JMenu();
                Izhod = new javax.swing.JMenuItem();
                Pomoc = new javax.swing.JMenu();
                pomoc = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Izposojevalnica avtomobilov Avtek");
                setFocusable(false);
                setLocationByPlatform(true);
                setPreferredSize(new java.awt.Dimension(670, 700));
                setResizable(false);
                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                formMouseEntered(evt);
                        }
                });

                status.setText("Status:");

                o_najemu.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
                o_najemu.setForeground(new java.awt.Color(51, 51, 255));
                o_najemu.setText("PODATKI O NAJEMU");

                datum_prevzema.setText("Datum prevzema:");

                datum_vrnitve.setText("Datum vrnitve:");

                dan_prevzema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
                dan_prevzema.setPreferredSize(new java.awt.Dimension(45, 20));

                mesec_prevzema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
                mesec_prevzema.setPreferredSize(new java.awt.Dimension(45, 20));

                leto_prevzema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));
                leto_prevzema.setPreferredSize(new java.awt.Dimension(65, 20));

                dan_vrnitve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
                dan_vrnitve.setSelectedIndex(1);
                dan_vrnitve.setPreferredSize(new java.awt.Dimension(45, 20));

                mesec_vrnitve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
                mesec_vrnitve.setPreferredSize(new java.awt.Dimension(45, 20));

                leto_vrnitve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017" }));
                leto_vrnitve.setPreferredSize(new java.awt.Dimension(65, 20));

                ura_prevzema.setText("Ura prevzema:");

                ura_vrnitve.setText("Ura vrnitve:");

                ura_prevzema_vnos.setModel(new javax.swing.SpinnerNumberModel(6, 6, 23, 1));

                ura_vrnitve_vnos.setModel(new javax.swing.SpinnerNumberModel(6, 6, 23, 1));

                mesto_prevzema.setText("Mesto prevzema:");

                mesto_prevzema_vnos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo mesto", "Murska Sobota", "Jesenice", "Portorož", "Letališče Brnik", "Letališče Maribor" }));
                mesto_prevzema_vnos.setPreferredSize(new java.awt.Dimension(71, 20));

                mesto_vrnitve.setText("Mesto vrnitve:");

                mesto_prevzema_vnos1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo mesto", "Murska Sobota", "Jesenice", "Portorož", "Letališče Brnik", "Letališče Maribor" }));
                mesto_prevzema_vnos1.setPreferredSize(new java.awt.Dimension(71, 20));

                javax.swing.GroupLayout najemLayout = new javax.swing.GroupLayout(najem);
                najem.setLayout(najemLayout);
                najemLayout.setHorizontalGroup(
                        najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(najemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(o_najemu)
                                        .addGroup(najemLayout.createSequentialGroup()
                                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(datum_vrnitve, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(datum_prevzema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(najemLayout.createSequentialGroup()
                                                                .addComponent(dan_prevzema, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(mesec_prevzema, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(leto_prevzema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(najemLayout.createSequentialGroup()
                                                                .addComponent(dan_vrnitve, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(mesec_vrnitve, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(leto_vrnitve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(51, 51, 51)
                                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ura_prevzema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ura_vrnitve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ura_prevzema_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ura_vrnitve_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(najemLayout.createSequentialGroup()
                                                .addComponent(mesto_prevzema)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mesto_prevzema_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(mesto_vrnitve)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mesto_prevzema_vnos1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                najemLayout.setVerticalGroup(
                        najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(najemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(o_najemu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(datum_prevzema)
                                        .addComponent(dan_prevzema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesec_prevzema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(leto_prevzema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ura_prevzema)
                                        .addComponent(ura_prevzema_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(datum_vrnitve)
                                        .addComponent(dan_vrnitve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesec_vrnitve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(leto_vrnitve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ura_vrnitve)
                                        .addComponent(ura_vrnitve_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(najemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mesto_prevzema)
                                        .addComponent(mesto_prevzema_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mesto_vrnitve)
                                        .addComponent(mesto_prevzema_vnos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                o_avtomobilu.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
                o_avtomobilu.setForeground(new java.awt.Color(51, 51, 255));
                o_avtomobilu.setText("PODATKI O AVTOMOBILU");

                velikost_avtomobila.setText("Velikost avtomobila:");

                tip_avtomobila.setText("Tip avtomobila:");

                buttonGroup1.add(majhen);
                majhen.setText("majhen");
                majhen.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                majhenActionPerformed(evt);
                        }
                });

                buttonGroup1.add(srednji);
                srednji.setText("srednji");
                srednji.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                srednjiActionPerformed(evt);
                        }
                });

                buttonGroup1.add(velik);
                velik.setText("velik");
                velik.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                velikActionPerformed(evt);
                        }
                });

                tip_majhen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Audi A1", "Toyota Auris", "Kia Picanto", "Citroen C2", "Renault Clio" }));
                tip_majhen.setEnabled(false);
                tip_majhen.setPreferredSize(new java.awt.Dimension(71, 20));

                tip_srednji.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MB C180", "Audi A5", "Toyota Avensis", "Honda Accord", "Škoda Octavia" }));
                tip_srednji.setEnabled(false);
                tip_srednji.setPreferredSize(new java.awt.Dimension(71, 20));

                tip_velik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toyota RAV4", "Kia Sportage", "Hyundai Tuscon", "BMW X6", "Audi Q7" }));
                tip_velik.setEnabled(false);
                tip_velik.setPreferredSize(new java.awt.Dimension(71, 20));

                menjalnik.setText("Menjalnik:");

                buttonGroup2.add(rocni);
                rocni.setText("ročni");

                buttonGroup2.add(avtomatski);
                avtomatski.setText("avtomatski");

                motor.setText("Motor:");

                buttonGroup3.add(bencinski);
                bencinski.setText("bencinski");

                buttonGroup3.add(dizelski);
                dizelski.setText("dizelski");

                javax.swing.GroupLayout avtomobilLayout = new javax.swing.GroupLayout(avtomobil);
                avtomobil.setLayout(avtomobilLayout);
                avtomobilLayout.setHorizontalGroup(
                        avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(avtomobilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(avtomobilLayout.createSequentialGroup()
                                                .addComponent(o_avtomobilu)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(avtomobilLayout.createSequentialGroup()
                                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(avtomobilLayout.createSequentialGroup()
                                                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(tip_avtomobila, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(velikost_avtomobila, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(majhen)
                                                                        .addComponent(tip_majhen, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(avtomobilLayout.createSequentialGroup()
                                                                .addComponent(menjalnik)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(rocni)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(avtomatski)))
                                                .addGap(45, 45, 45)
                                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(avtomobilLayout.createSequentialGroup()
                                                                .addComponent(motor)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(bencinski)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(dizelski)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(avtomobilLayout.createSequentialGroup()
                                                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(srednji)
                                                                        .addComponent(tip_srednji, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(velik)
                                                                        .addComponent(tip_velik, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(59, Short.MAX_VALUE))))))
                );
                avtomobilLayout.setVerticalGroup(
                        avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(avtomobilLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(o_avtomobilu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(velikost_avtomobila)
                                        .addComponent(majhen)
                                        .addComponent(srednji)
                                        .addComponent(velik))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tip_avtomobila)
                                        .addComponent(tip_majhen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tip_srednji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tip_velik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(avtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(menjalnik)
                                        .addComponent(rocni)
                                        .addComponent(avtomatski)
                                        .addComponent(motor)
                                        .addComponent(bencinski)
                                        .addComponent(dizelski))
                                .addContainerGap(12, Short.MAX_VALUE))
                );

                cena_za_dan.setText("Cena najema izbranega avtomobila za en dan znaša:");

                cena_na_dan_izpis.setBackground(new java.awt.Color(153, 255, 153));
                cena_na_dan_izpis.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cena_na_dan_izpisActionPerformed(evt);
                        }
                });

                skupna_cena.setText("Skupna cena:");

                skupna_cena_izpis.setBackground(new java.awt.Color(153, 255, 153));

                podatki.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                podatkiMouseEntered(evt);
                        }
                });

                osebni_podatki.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
                osebni_podatki.setForeground(new java.awt.Color(51, 51, 255));
                osebni_podatki.setText("OSEBNI PODATKI");

                ime.setText("Ime:");

                priimek.setText("Priimek:");

                starost.setText("Starost:");

                starost_vnos.setModel(new javax.swing.SpinnerNumberModel(18, 18, 99, 1));

                naslov.setText("Naslov:");

                kraj.setText("Kraj:");

                postna_st.setText("Poštna številka:");

                mail.setText("E-mail:");

                telefon.setText("Telefon:");

                cas_izpita.setText("Koliko let že imate vozniški izpit?");

                cas_izpita_vnos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 81, 1));

                dodatno_zavarovanje.setText("Želim dodatno avtomobilsko zavarovanje (2€ / dan):");

                dod_zavarovanje.setPreferredSize(new java.awt.Dimension(104, 20));

                javax.swing.GroupLayout podatkiLayout = new javax.swing.GroupLayout(podatki);
                podatki.setLayout(podatkiLayout);
                podatkiLayout.setHorizontalGroup(
                        podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(podatkiLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(osebni_podatki)
                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, podatkiLayout.createSequentialGroup()
                                                                        .addComponent(mail)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(mail_vnos))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, podatkiLayout.createSequentialGroup()
                                                                        .addComponent(naslov)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(naslov_vnos))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, podatkiLayout.createSequentialGroup()
                                                                        .addComponent(ime)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(ime_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(40, 40, 40)
                                                                        .addComponent(priimek)))
                                                        .addComponent(cas_izpita))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                                                .addComponent(priimek_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(40, 40, 40)
                                                                                .addComponent(starost))
                                                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                                                .addComponent(kraj)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(kraj_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(starost_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                                                .addComponent(postna_st)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(postna_st_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                                .addComponent(telefon)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(telefon_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(cas_izpita_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                .addComponent(dodatno_zavarovanje)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dod_zavarovanje, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(40, Short.MAX_VALUE))
                );
                podatkiLayout.setVerticalGroup(
                        podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, podatkiLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(osebni_podatki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ime)
                                        .addComponent(ime_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(priimek)
                                        .addComponent(priimek_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(starost)
                                        .addComponent(starost_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(naslov)
                                        .addComponent(naslov_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kraj)
                                        .addComponent(kraj_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(postna_st)
                                        .addComponent(postna_st_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mail)
                                        .addComponent(mail_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(telefon)
                                        .addComponent(telefon_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(podatkiLayout.createSequentialGroup()
                                                .addGroup(podatkiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cas_izpita)
                                                        .addComponent(cas_izpita_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(dodatno_zavarovanje))
                                        .addComponent(dod_zavarovanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                );

                nacin_placila.setText("Način plačila:");

                buttonGroup4.add(gotovina);
                gotovina.setText("z gotovino ob prevzemu");
                gotovina.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                gotovinaActionPerformed(evt);
                        }
                });

                buttonGroup4.add(kartica);
                kartica.setText("s kreditno kartico takoj");
                kartica.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                karticaActionPerformed(evt);
                        }
                });

                st_kreditne_kartice.setText("Številka kreditne kartice:");
                st_kreditne_kartice.setEnabled(false);

                skrita_st_kreditne_kartice.setText("jPasswordField1");
                skrita_st_kreditne_kartice.setEnabled(false);

                vidna_st_kreditne_kartice.setEnabled(false);

                ccv.setText("CCV koda:");
                ccv.setEnabled(false);

                ccv_vnos.setText("jPasswordField2");
                ccv_vnos.setEnabled(false);

                placaj.setBackground(new java.awt.Color(153, 255, 153));
                placaj.setText("Plačaj");
                placaj.setEnabled(false);
                placaj.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                placajActionPerformed(evt);
                        }
                });

                potrdi.setBackground(new java.awt.Color(153, 255, 153));
                potrdi.setText("Potrdi");
                potrdi.setEnabled(false);
                potrdi.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                potrdiActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout placiloLayout = new javax.swing.GroupLayout(placilo);
                placilo.setLayout(placiloLayout);
                placiloLayout.setHorizontalGroup(
                        placiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(placiloLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(placiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(placiloLayout.createSequentialGroup()
                                                .addComponent(nacin_placila)
                                                .addGap(18, 18, 18)
                                                .addComponent(gotovina)
                                                .addGap(18, 18, 18)
                                                .addComponent(kartica))
                                        .addGroup(placiloLayout.createSequentialGroup()
                                                .addComponent(st_kreditne_kartice)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(skrita_st_kreditne_kartice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(vidna_st_kreditne_kartice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ccv)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ccv_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addGroup(placiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(placaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(potrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                placiloLayout.setVerticalGroup(
                        placiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(placiloLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(placiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nacin_placila)
                                        .addComponent(gotovina)
                                        .addComponent(kartica)
                                        .addComponent(potrdi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(placiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(st_kreditne_kartice)
                                        .addComponent(skrita_st_kreditne_kartice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vidna_st_kreditne_kartice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ccv)
                                        .addComponent(ccv_vnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(placaj))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                Datoteka.setMnemonic(KeyEvent.VK_D);
                Datoteka.setText("Datoteka");

                Izhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
                Izhod.setText("Izhod");
                Izhod.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                IzhodActionPerformed(evt);
                        }
                });
                Datoteka.add(Izhod);

                jMenuBar1.add(Datoteka);

                Pomoc.setMnemonic(KeyEvent.VK_P);
                Pomoc.setText("Pomoč");
                Pomoc.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                PomocActionPerformed(evt);
                        }
                });

                pomoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
                pomoc.setText("Pomoč");
                pomoc.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                pomocActionPerformed(evt);
                        }
                });
                Pomoc.add(pomoc);

                jMenuBar1.add(Pomoc);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(najem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(avtomobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(cena_za_dan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cena_na_dan_izpis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(skupna_cena)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(skupna_cena_izpis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(podatki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5)
                        .addComponent(placilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(najem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avtomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cena_za_dan)
                                        .addComponent(skupna_cena_izpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(skupna_cena)
                                        .addComponent(cena_na_dan_izpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(podatki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(placilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void PomocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PomocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PomocActionPerformed

    private void pomocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomocActionPerformed
        // TODO add your handling code here:
        status.setText("Status: Za pomoč pokličite na tel. številko 01 501 97 69 ali običite spletno stran www.avtek.si");
    }//GEN-LAST:event_pomocActionPerformed

    private void IzhodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzhodActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_IzhodActionPerformed

    private void majhenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majhenActionPerformed
        // TODO add your handling code here:
        if (majhen.isSelected()) {
            tip_majhen.setEnabled(true);
            tip_srednji.setEnabled(false);
            tip_velik.setEnabled(false);
        }
    }//GEN-LAST:event_majhenActionPerformed

    private void srednjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srednjiActionPerformed
        // TODO add your handling code here:
        if (srednji.isSelected()) {
            tip_majhen.setEnabled(false);
            tip_srednji.setEnabled(true);
            tip_velik.setEnabled(false);
        }
    }//GEN-LAST:event_srednjiActionPerformed

    private void velikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velikActionPerformed
        // TODO add your handling code here:
        if (velik.isSelected()) {
            tip_majhen.setEnabled(false);
            tip_srednji.setEnabled(false);
            tip_velik.setEnabled(true);
        }
    }//GEN-LAST:event_velikActionPerformed

    private void gotovinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotovinaActionPerformed
        // TODO add your handling code here:
        if (gotovina.isSelected()) {
            potrdi.setEnabled(true);
            st_kreditne_kartice.setEnabled(false);
            skrita_st_kreditne_kartice.setEnabled(false);
            vidna_st_kreditne_kartice.setEnabled(false);
            ccv.setEnabled(false);
            ccv_vnos.setEnabled(false);
            placaj.setEnabled(false);
        }
    }//GEN-LAST:event_gotovinaActionPerformed

    private void karticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karticaActionPerformed
        // TODO add your handling code here:
        if (kartica.isSelected()) {
            potrdi.setEnabled(false);
            st_kreditne_kartice.setEnabled(true);
            skrita_st_kreditne_kartice.setEnabled(true);
            vidna_st_kreditne_kartice.setEnabled(true);
            ccv.setEnabled(true);
            ccv_vnos.setEnabled(true);
            placaj.setEnabled(true);
        }
    }//GEN-LAST:event_karticaActionPerformed

    private void cena_na_dan_izpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cena_na_dan_izpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cena_na_dan_izpisActionPerformed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        boolean izpolnjeno = false;
        
        if ((majhen.isSelected() || srednji.isSelected() || velik.isSelected()) && (rocni.isSelected() || avtomatski.isSelected()) 
               && (bencinski.isSelected() || dizelski.isSelected())) {
            izpolnjeno = true;
        }
        
        if (!izpolnjeno) {
            status.setForeground(Color.black);
            status.setText("Status: Izpolnite podatke.");
        }
        else {
            int dP = dan_prevzema.getSelectedIndex() +1;
            int mP = mesec_prevzema.getSelectedIndex() +1;
            int lP = leto_prevzema.getSelectedIndex() +2015;
            int dV = dan_vrnitve.getSelectedIndex() +1;
            int mV = mesec_vrnitve.getSelectedIndex() +1;
            int lV = leto_vrnitve.getSelectedIndex() +2015;
            int uP = (int) ura_prevzema_vnos.getValue();
            int uV = (int) ura_vrnitve_vnos.getValue();
            
            boolean pravilno = true;

            if ((lV < lP) || (lV == lP && mV < mP) || (lV == lP && mV == mP && dV < dP) || (lV == lP && mV == mP && dV == dP && uV <= uP)) {
                status.setForeground(Color.red);
                status.setText("Status: Datum vrnitve je pred datumom prevzema.");
                pravilno = false;
                cena_na_dan_izpis.setText("");
                skupna_cena_izpis.setText("");
            }
            if ((lV == lP && mV-mP > 1) || (lV == lP && mV-mP == 1 && dV > dP) || (lV > lP && mV > 1)) {
                status.setForeground(Color.red);
                status.setText("Status: Največji možen čas izposoje je en mesec.");
                pravilno = false;
                cena_na_dan_izpis.setText("");
                skupna_cena_izpis.setText("");
            }

            if (pravilno) {
                int stDni = 0;
                if (mV == mP) {
                    stDni = dV - dP +1;
                }
                else {
                    if (mP == 2) {
                        stDni = 28 - dP + dV +1;
                    }
                    else if (mP == 4 || mP == 6 || mP == 9 || mP == 11) {
                        stDni = 30 - dP + dV +1;
                    }
                    else {
                        stDni = 31 - dP + dV +1;
                    }
                }

                int cena = 0;
                if (majhen.isSelected())  cena = 70;
                else if (srednji.isSelected())  cena = 100;
                else if (velik.isSelected())  cena = 150;
                if (avtomatski.isSelected())  cena += 10;
                if (dizelski.isSelected())  cena += 15;
                cena_na_dan_izpis.setText(cena + " €");

                int skupnaCena = cena * stDni; 
                if (dod_zavarovanje.isSelected()) skupnaCena += 2*stDni;

                skupna_cena_izpis.setText(skupnaCena +" €");
                
                if (!placano) {
                    status.setForeground(Color.black);
                    status.setText("Status: Skupna cena trenutno izbranega avtomobila za izbrano obdobje je " + skupnaCena + " €.");
                }
            }
        }
    }//GEN-LAST:event_formMouseEntered

    boolean placano = false;
    
    private void placajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placajActionPerformed
        // TODO add your handling code here:
        int i = ime_vnos.getText().length();
        int p = priimek_vnos.getText().length();
        int n = naslov_vnos.getText().length();
        int k = kraj_vnos.getText().length();
        int pos = postna_st_vnos.getText().length();
        int e = mail_vnos.getText().length();
        int t = telefon_vnos.getText().length();
        boolean vredu = true;
        
        if (!(majhen.isSelected() || srednji.isSelected() || velik.isSelected())) {
            status.setForeground(Color.red);
            status.setText("Status: Avto ni izbran.");
            vredu = false;
        }
        if (!(bencinski.isSelected() || dizelski.isSelected())) {
            status.setForeground(Color.red);
            status.setText("Status: Tip motorja ni izbran.");
            vredu = false;
        }
        if (!(rocni.isSelected() || avtomatski.isSelected())) {
            status.setForeground(Color.red);
            status.setText("Status: Tip menjalnika ni izbran.");
            vredu = false;
        }
        
        if (i==0 || p==0 || n==0 || k==0 || pos==0 || e==0 || t==0) {
            status.setForeground(Color.red);
            status.setText("Status: Izpolnite vse osebne podatke.");
            vredu = false;
        }
        if (skrita_st_kreditne_kartice.getText().length() < 12 || vidna_st_kreditne_kartice.getText().length() < 4) {
            status.setForeground(Color.red);
            status.setText("Status: Številka kreditne kartice nima dovolj znakov.");
            vredu = false;
        }
        if (skrita_st_kreditne_kartice.getText().length() > 12 || vidna_st_kreditne_kartice.getText().length() > 4) {
            status.setForeground(Color.red);
            status.setText("Status: Številka kreditne kartice ima preveč znakov.");
            vredu =  false;
        }
        if (ccv_vnos.getText().length() != 4) {
            status.setForeground(Color.red);
            status.setText("Status: CCV koda mora imeti 4 znake.");
            vredu = false;
        }
        if (vredu && skrita_st_kreditne_kartice.getText().length() == 12 && vidna_st_kreditne_kartice.getText().length() == 4 && ccv_vnos.getText().length() == 4) {
            String prevzem = mesto_prevzema_vnos.getName();
            status.setForeground(new Color(0,150,50));
            status.setText("Status: Plačilo je uspešno opravljeno. Hvala za zaupanje.");
            placano = true;
        }
    }//GEN-LAST:event_placajActionPerformed

    private void potrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potrdiActionPerformed
        // TODO add your handling code here:
        int i = ime_vnos.getText().length();
        int p = priimek_vnos.getText().length();
        int n = naslov_vnos.getText().length();
        int k = kraj_vnos.getText().length();
        int pos = postna_st_vnos.getText().length();
        int e = mail_vnos.getText().length();
        int t = telefon_vnos.getText().length();
        boolean uredu = true;
        
        if (i==0 || p==0 || n==0 || k==0 || pos==0 || e==0 || t==0) {
            status.setForeground(Color.red);
            status.setText("Status: Izpolnite vse osebne podatke.");
            uredu = false;
        }
        if (!(majhen.isSelected() || srednji.isSelected() || velik.isSelected())) {
            status.setForeground(Color.red);
            status.setText("Status: Avto ni izbran.");
            uredu = false;
        }
        if (!(bencinski.isSelected() || dizelski.isSelected())) {
            status.setForeground(Color.red);
            status.setText("Status: Tip motorja ni izbran.");
            uredu = false;
        }
        if (!(rocni.isSelected() || avtomatski.isSelected())) {
            status.setForeground(Color.red);
            status.setText("Status: Tip menjalnika ni izbran.");
            uredu = false;
        }
        
        if (uredu) {
            status.setForeground(new Color(0,150,50));
            status.setText("Status: Celoten znesek najema boste poravnali ob prevzemu avtomobila. Hvala za zaupanje.");
            placano = true;
        }
        
    }//GEN-LAST:event_potrdiActionPerformed

    private void podatkiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_podatkiMouseEntered
        // TODO add your handling code here:
        int i = ime_vnos.getText().length();
        int p = priimek_vnos.getText().length();
        int n = naslov_vnos.getText().length();
        int k = kraj_vnos.getText().length();
        int pos = postna_st_vnos.getText().length();
        int e = mail_vnos.getText().length();
        int t = telefon_vnos.getText().length();
        
        String temp = status.getText();
        Color tmp = status.getForeground();
        
        if (i==0 || p==0 || n==0 || k==0 || pos==0 || e==0 || t==0) {
            status.setForeground(Color.red);
            status.setText("Status: Izpolnite vse osebne podatke.");
        }
        else {
            int posta = postna_st_vnos.getText().length();
            if (posta != 4) {
                status.setForeground(Color.red);
                status.setText("Status: Vpisana poštna številka ni veljavna.");
            }
            for (int in=0; in<posta; in++) {
                if (!postna_st_vnos.getText().matches("[0-9]+")) {
                    status.setForeground(Color.red);
                    status.setText("Status: Vpisana poštna številka ni veljavna.");
                    break;
                }
            }
            
            boolean alfa = false;
            int mail = mail_vnos.getText().length();
            for (int j=0; j<mail; j++) {
                if (mail_vnos.getText().charAt(j) == '@') {
                    alfa = true;
                    break;
                }
            }
            if (!alfa) {
                status.setForeground(Color.red);
                status.setText("Status: Vpisan e-mail naslov ni pravilen.");
            }
        }
    }//GEN-LAST:event_podatkiMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzposojevalnicaAvtomobilov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzposojevalnicaAvtomobilov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzposojevalnicaAvtomobilov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzposojevalnicaAvtomobilov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IzposojevalnicaAvtomobilov().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu Datoteka;
        private javax.swing.JMenuItem Izhod;
        private javax.swing.JMenu Pomoc;
        private javax.swing.JRadioButton avtomatski;
        private javax.swing.JPanel avtomobil;
        private javax.swing.JRadioButton bencinski;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.ButtonGroup buttonGroup2;
        private javax.swing.ButtonGroup buttonGroup3;
        private javax.swing.ButtonGroup buttonGroup4;
        private javax.swing.JLabel cas_izpita;
        private javax.swing.JSpinner cas_izpita_vnos;
        private javax.swing.JLabel ccv;
        private javax.swing.JPasswordField ccv_vnos;
        private javax.swing.JTextField cena_na_dan_izpis;
        private javax.swing.JLabel cena_za_dan;
        private javax.swing.JComboBox dan_prevzema;
        private javax.swing.JComboBox dan_vrnitve;
        private javax.swing.JLabel datum_prevzema;
        private javax.swing.JLabel datum_vrnitve;
        private javax.swing.JRadioButton dizelski;
        private javax.swing.JCheckBox dod_zavarovanje;
        private javax.swing.JLabel dodatno_zavarovanje;
        private javax.swing.JRadioButton gotovina;
        private javax.swing.JLabel ime;
        private javax.swing.JTextField ime_vnos;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private javax.swing.JSeparator jSeparator4;
        private javax.swing.JSeparator jSeparator5;
        private javax.swing.JSeparator jSeparator6;
        private javax.swing.JRadioButton kartica;
        private javax.swing.JLabel kraj;
        private javax.swing.JTextField kraj_vnos;
        private javax.swing.JComboBox leto_prevzema;
        private javax.swing.JComboBox leto_vrnitve;
        private javax.swing.JLabel mail;
        private javax.swing.JTextField mail_vnos;
        private javax.swing.JRadioButton majhen;
        private javax.swing.JLabel menjalnik;
        private javax.swing.JComboBox mesec_prevzema;
        private javax.swing.JComboBox mesec_vrnitve;
        private javax.swing.JLabel mesto_prevzema;
        private javax.swing.JComboBox mesto_prevzema_vnos;
        private javax.swing.JComboBox mesto_prevzema_vnos1;
        private javax.swing.JLabel mesto_vrnitve;
        private javax.swing.JLabel motor;
        private javax.swing.JLabel nacin_placila;
        private javax.swing.JPanel najem;
        private javax.swing.JLabel naslov;
        private javax.swing.JTextField naslov_vnos;
        private javax.swing.JLabel o_avtomobilu;
        private javax.swing.JLabel o_najemu;
        private javax.swing.JLabel osebni_podatki;
        private javax.swing.JButton placaj;
        private javax.swing.JPanel placilo;
        private javax.swing.JPanel podatki;
        private javax.swing.JMenuItem pomoc;
        private javax.swing.JLabel postna_st;
        private javax.swing.JTextField postna_st_vnos;
        private javax.swing.JButton potrdi;
        private javax.swing.JLabel priimek;
        private javax.swing.JTextField priimek_vnos;
        private javax.swing.JRadioButton rocni;
        private javax.swing.JPasswordField skrita_st_kreditne_kartice;
        private javax.swing.JLabel skupna_cena;
        private javax.swing.JTextField skupna_cena_izpis;
        private javax.swing.JRadioButton srednji;
        private javax.swing.JLabel st_kreditne_kartice;
        private javax.swing.JLabel starost;
        private javax.swing.JSpinner starost_vnos;
        private javax.swing.JLabel status;
        private javax.swing.JLabel telefon;
        private javax.swing.JTextField telefon_vnos;
        private javax.swing.JLabel tip_avtomobila;
        private javax.swing.JComboBox tip_majhen;
        private javax.swing.JComboBox tip_srednji;
        private javax.swing.JComboBox tip_velik;
        private javax.swing.JLabel ura_prevzema;
        private javax.swing.JSpinner ura_prevzema_vnos;
        private javax.swing.JLabel ura_vrnitve;
        private javax.swing.JSpinner ura_vrnitve_vnos;
        private javax.swing.JRadioButton velik;
        private javax.swing.JLabel velikost_avtomobila;
        private javax.swing.JTextField vidna_st_kreditne_kartice;
        // End of variables declaration//GEN-END:variables
}
